"""Generate a Tailwind CSS entry file for projects that build their own CSS.

django-mvp ships a prebuilt stylesheet that covers every packaged component.
Projects that use their own Tailwind classes (in their own templates) must
rebuild CSS themselves, scanning their templates, django-mvp's packaged
templates and the django-mvp-forms package that draws forms. This command writes a ready-to-use Tailwind v4 entry file
with the package paths resolved for the current environment::

    python manage.py mvp_tailwind > assets/tailwind.css
    npx @tailwindcss/cli -i assets/tailwind.css -o static/css/app.css --minify

Re-run after upgrading django-mvp or moving environments — the generated
paths are machine-specific.
"""

from pathlib import Path

from django.core.management.base import BaseCommand

import mvp
import mvp_forms

# mvp is distributed without an __init__.py (implicit namespace package), so
# __file__ is None — resolve the package directory from __path__ instead.
PACKAGE_DIR = Path(next(iter(mvp.__path__))).resolve()
# Scanned whole: django-mvp-forms writes classes in its template tags as well
# as its templates.
FORMS_DIR = Path(mvp_forms.__file__).resolve().parent

ENTRY_TEMPLATE = """\
/* Tailwind entry for a django-mvp project.
 * Generated by `python manage.py mvp_tailwind`. Re-run after upgrading
 * django-mvp or moving environments (the paths below are machine-specific).
 *
 * Requires: npm install -D tailwindcss @tailwindcss/cli daisyui
 * Build:    npx @tailwindcss/cli -i <this file> -o static/css/app.css --minify
 */
@import "tailwindcss" source(none);
@plugin "daisyui" {{
  themes: all;
}}

/* django-mvp preset: drawer-state variants, safelisted breakpoint classes,
   and icon-rail CSS. */
@import "{preset}";

/* Generate the classes used by django-mvp's packaged templates. */
@source "{templates}";

/* Generate the classes django-mvp-forms writes when it draws a form. */
@source "{forms}";

/* Your project: add one @source line per directory containing templates or
   code that uses Tailwind classes. Paths are relative to this file. */
@source "./templates";
"""


class Command(BaseCommand):
    """Print a Tailwind v4 entry file with the package's paths resolved."""

    help = (
        "Print a Tailwind v4 entry stylesheet that scans django-mvp's packaged "
        "templates alongside your own. Redirect to a file, e.g. "
        "`python manage.py mvp_tailwind > assets/tailwind.css`."
    )

    def add_arguments(self, parser):
        """Add ``--paths``."""
        parser.add_argument(
            "--paths",
            action="store_true",
            help=(
                "Print only the resolved package paths (preset CSS, templates "
                "directory and the django-mvp-forms package), one per line, "
                "for wiring a custom entry file."
            ),
        )

    def handle(self, *args, **options):
        """Print the entry file, or only the package paths with ``--paths``."""
        preset = (PACKAGE_DIR / "tailwind" / "base.css").as_posix()
        templates = (PACKAGE_DIR / "templates").as_posix()
        forms = FORMS_DIR.as_posix()

        if options["paths"]:
            self.stdout.write(preset)
            self.stdout.write(templates)
            self.stdout.write(forms)
            return

        self.stdout.write(
            ENTRY_TEMPLATE.format(preset=preset, templates=templates, forms=forms)
        )
