# Generated by Django 5.2.11 on 2026-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_category_archived_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=200, null=True
            ),
        ),
    ]
