# Generated by Django 5.2.16 on 2026-08-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_alter_product_barcode_alter_product_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                help_text="The product this order line is for.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="demo.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many units of the product were ordered.",
                verbose_name="quantity",
            ),
        ),
    ]
