# Generated by Django 5.2.16 on 2026-08-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_orderline_verbose_name_and_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The project's name.", max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="The note's text.", max_length=200, verbose_name='text')),
                ('project', models.ForeignKey(help_text='The project this note was written for.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='demo.project', verbose_name='project')),
                ('related_project', models.ForeignKey(blank=True, help_text='A second project this note cross-references, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_notes', to='demo.project', verbose_name='related project')),
            ],
            options={
                'verbose_name': 'project note',
                'verbose_name_plural': 'project notes',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The task's title.", max_length=200, verbose_name='title')),
                ('project', models.ForeignKey(help_text='The project this task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='demo.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project task',
                'verbose_name_plural': 'project tasks',
            },
        ),
    ]
