# Generated by Django 5.2.17 on 2026-09-17 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_project_projectnote_projecttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units of the product were shipped.', verbose_name='quantity')),
                ('product', models.ForeignKey(help_text='The product this shipment line is for.', on_delete=django.db.models.deletion.RESTRICT, related_name='shipment_lines', to='demo.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'shipment line',
                'verbose_name_plural': 'shipment lines',
            },
        ),
    ]
