name: Build

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  call-build:
    uses: django-mvp/shared/.github/workflows/build.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    with:
      source-dir: mvp
    secrets: inherit
