name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Update Changelog
        uses: django-mvp/shared/.github/actions/update-changelog@main
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
