name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'mvp/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/tests.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'mvp/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

jobs:
  call-tests:
    uses: django-mvp/workflows/workflows/tests.yml@main
    with:
      coverage-package: mvp
    secrets: inherit
